apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivote-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: setup-vote
  source:
    path: prod
    repoURL: https://github.com/dhruv-dave/argo-labs.git
    targetRevision: release
  syncPolicy:
    automated:
      enabled: true
      prune: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true